[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
tic_tac_toe = "Fqq3Fko3wFvAWhhzXtrbzY5Kf9YQmdwiSCpUagyG7BMr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
